# Generated by Django 4.2.30 on 2026-09-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location_block', models.CharField(choices=[('BLOCK_1', 'Block 1 — Library / Academic'), ('BLOCK_2', 'Block 2 — Chemistry Labs'), ('BLOCK_3', 'Block 3 — Mechanical Workshop'), ('BLOCK_4', 'Block 4 — Computer Science'), ('BLOCK_5', 'Block 5 — Administration'), ('HOSTEL_A', 'Hostel A — Residential'), ('HOSTEL_B', 'Hostel B — Residential'), ('MAIN_GATE', 'Main Gate — Campus Entrance'), ('CAFETERIA', 'Cafeteria — High Occupancy'), ('AUDITORIUM', 'Auditorium — Large Gathering'), ('SPORTS_GROUND', 'Sports Ground — Open Area'), ('HEALTH_CENTRE', 'Health Centre — Medical Response'), ('SECURITY_ROOM', 'Security Room — Command Centre'), ('SUBSTATION', 'Electrical Substation — Infrastructure'), ('OTHER', 'Other')], max_length=50)),
                ('coverage_description', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Under Maintenance')], default='ONLINE', max_length=15)),
                ('rtsp_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CCTVEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('SMOKE_FIRE', 'Possible Smoke / Fire'), ('CROWD_FORMATION', 'Crowd Formation'), ('RESTRICTED_ENTRY', 'Restricted Area Entry'), ('FALL_COLLAPSE', 'Fall / Collapse Detection'), ('UNUSUAL_MOVEMENT', 'Unusual Crowd Movement'), ('OTHER', 'Other')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='cameras.camera')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
