# Generated by Django 4.2.30 on 2026-09-16 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('incident_type', models.CharField(choices=[('FIRE_SMOKE', 'Fire / Smoke'), ('MEDICAL', 'Medical Emergency'), ('CHEMICAL', 'Chemical / Laboratory Hazard'), ('SECURITY_THREAT', 'Security Threat / Intrusion'), ('ELECTRICAL', 'Electrical / Infrastructure'), ('VIOLENCE_CROWD', 'Violence / Crowd Disturbance'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('location', models.CharField(choices=[('BLOCK_1', 'Block 1 — Library / Academic'), ('BLOCK_2', 'Block 2 — Chemistry Labs'), ('BLOCK_3', 'Block 3 — Mechanical Workshop'), ('BLOCK_4', 'Block 4 — Computer Science'), ('BLOCK_5', 'Block 5 — Administration'), ('HOSTEL_A', 'Hostel A — Residential'), ('HOSTEL_B', 'Hostel B — Residential'), ('MAIN_GATE', 'Main Gate — Campus Entrance'), ('CAFETERIA', 'Cafeteria — High Occupancy'), ('AUDITORIUM', 'Auditorium — Large Gathering'), ('SPORTS_GROUND', 'Sports Ground — Open Area'), ('HEALTH_CENTRE', 'Health Centre — Medical Response'), ('SECURITY_ROOM', 'Security Room — Command Centre'), ('SUBSTATION', 'Electrical Substation — Infrastructure'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('CLASSIFIED', 'Classified'), ('PRIORITIZED', 'Prioritized'), ('AWAITING_APPROVAL', 'Awaiting Operator Approval'), ('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='REPORTED', max_length=20)),
                ('people_exposed', models.IntegerField(default=0)),
                ('spread_potential', models.CharField(blank=True, max_length=20)),
                ('severity_factors', models.JSONField(default=list)),
                ('required_capabilities', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('priority', models.CharField(choices=[('P0', 'P0 — Critical (90–100)'), ('P1', 'P1 — Serious (75–89)'), ('P2', 'P2 — Significant (50–74)'), ('P3', 'P3 — Lower Urgency (0–49)')], default='P3', max_length=5)),
                ('risk_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-risk_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('actor_label', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('STUDENT', 'Student'), ('FACULTY', 'Faculty'), ('SECURITY', 'Security Staff'), ('CCTV', 'CCTV System'), ('OPERATOR', 'Operator')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('BLOCK_1', 'Block 1 — Library / Academic'), ('BLOCK_2', 'Block 2 — Chemistry Labs'), ('BLOCK_3', 'Block 3 — Mechanical Workshop'), ('BLOCK_4', 'Block 4 — Computer Science'), ('BLOCK_5', 'Block 5 — Administration'), ('HOSTEL_A', 'Hostel A — Residential'), ('HOSTEL_B', 'Hostel B — Residential'), ('MAIN_GATE', 'Main Gate — Campus Entrance'), ('CAFETERIA', 'Cafeteria — High Occupancy'), ('AUDITORIUM', 'Auditorium — Large Gathering'), ('SPORTS_GROUND', 'Sports Ground — Open Area'), ('HEALTH_CENTRE', 'Health Centre — Medical Response'), ('SECURITY_ROOM', 'Security Room — Command Centre'), ('SUBSTATION', 'Electrical Substation — Infrastructure'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=255)),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='evidence/')),
                ('additional_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
