# Generated by Django 4.2.30 on 2026-09-16 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='can_resolve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='response_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='security_approval_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='security_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='security_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending Security Review'), ('INVESTIGATING', 'Under Security Check'), ('SECURITY_APPROVED', 'Approved by Security'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING_REVIEW', max_length=25),
        ),
        migrations.CreateModel(
            name='IncidentSeparationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PERIMETER_CORDON', 'Perimeter Cordon & Boundary Separation'), ('SECTOR_ISOLATION', 'Sector & Zone Isolation'), ('ACCESS_LOCKDOWN', 'Access Point Lockdown'), ('CROWD_DIVERSION', 'Crowd & Traffic Diversion'), ('HVAC_VENTILATION', 'HVAC & Ventilation Shutoff'), ('UTILITY_ISOLATION', 'Utility / Power / Gas Cutoff'), ('EVACUATION_CLEARANCE', 'Evacuation Clearance & Separation')], default='PERIMETER_CORDON', max_length=35)),
                ('description', models.TextField(blank=True)),
                ('target_location', models.CharField(blank=True, max_length=150)),
                ('assigned_role', models.CharField(blank=True, max_length=50)),
                ('priority', models.CharField(choices=[('URGENT', 'Urgent / Immediate'), ('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='HIGH', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_separation_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_separation_tasks', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_tasks', to='incidents.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
