# Generated by Django 4.2.30 on 2026-09-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('MEDICAL', 'Medical Team'), ('FIRE', 'Fire Response Team'), ('HAZMAT', 'Hazmat / EHS Team'), ('SECURITY', 'Security Response Team'), ('FACILITIES', 'Facilities / Maintenance Team')], max_length=20)),
                ('capabilities', models.JSONField(default=list)),
                ('location', models.CharField(choices=[('BLOCK_1', 'Block 1 — Library / Academic'), ('BLOCK_2', 'Block 2 — Chemistry Labs'), ('BLOCK_3', 'Block 3 — Mechanical Workshop'), ('BLOCK_4', 'Block 4 — Computer Science'), ('BLOCK_5', 'Block 5 — Administration'), ('HOSTEL_A', 'Hostel A — Residential'), ('HOSTEL_B', 'Hostel B — Residential'), ('MAIN_GATE', 'Main Gate — Campus Entrance'), ('CAFETERIA', 'Cafeteria — High Occupancy'), ('AUDITORIUM', 'Auditorium — Large Gathering'), ('SPORTS_GROUND', 'Sports Ground — Open Area'), ('HEALTH_CENTRE', 'Health Centre — Medical Response'), ('SECURITY_ROOM', 'Security Room — Command Centre'), ('SUBSTATION', 'Electrical Substation — Infrastructure'), ('OTHER', 'Other')], default='SECURITY_ROOM', max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'On Assignment'), ('OFFLINE', 'Offline / Unavailable')], default='AVAILABLE', max_length=15)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=15)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
