# Generated by Django 4.2.30 on 2026-09-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resourceassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('DISPATCHED', 'Dispatched'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('COMPLETED', 'Completed'), ('REVOKED', 'Revoked')], default='ASSIGNED', max_length=15),
        ),
    ]
