# Generated by Django 4.2.30 on 2026-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourceassignment_revocation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceassignment',
            name='casualties_treated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='completion_report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceassignment',
            name='hazard_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
