/**
 * Campus Tactical Master Plan Data & Coordinate Mapping
 * Defines the geometric blueprint footprints for all 14 synthetic campus locations,
 * CCTV surveillance camera anchors with FOV angles, and resource home bases.
 */

export const CAMPUS_VIEWBOX = { width: 1200, height: 800 };

export const CAMPUS_LOCATIONS = {
  BLOCK_1: {
    id: 'BLOCK_1',
    name: 'Block 1',
    subtitle: 'Library & Academic Center',
    category: 'ACADEMIC',
    type: 'Academic / High Traffic',
    occupancy: 'High (400–600)',
    x: 120,
    y: 110,
    w: 200,
    h: 150,
    center: { x: 220, y: 185 },
    icon: 'BookOpen',
    hazardRating: 'LOW',
    color: '#3B82F6',
    description: 'Central multi-tier library, study carrels, digital research archives, and lecture halls 101–108.',
    cameras: ['CAM-01', 'CAM-02', 'CAM-03'],
  },
  BLOCK_2: {
    id: 'BLOCK_2',
    name: 'Block 2',
    subtitle: 'Chemistry & Bio Labs',
    category: 'HAZARD',
    type: 'Laboratory / Chemical Hazard',
    occupancy: 'Medium (150–250)',
    x: 390,
    y: 90,
    w: 230,
    h: 170,
    center: { x: 505, y: 175 },
    icon: 'FlaskConical',
    hazardRating: 'HIGH',
    color: '#EF4444',
    description: 'Organic synthesis labs, chemical storage bunkers, fume hood extraction systems, and bio-specimen containment.',
    cameras: ['CAM-04', 'CAM-05', 'CAM-06'],
  },
  BLOCK_3: {
    id: 'BLOCK_3',
    name: 'Block 3',
    subtitle: 'Mechanical Workshops',
    category: 'INDUSTRIAL',
    type: 'Engineering / Workshop',
    occupancy: 'Medium (120–200)',
    x: 690,
    y: 100,
    w: 210,
    h: 150,
    center: { x: 795, y: 175 },
    icon: 'Wrench',
    hazardRating: 'MEDIUM',
    color: '#F59E0B',
    description: 'CNC milling bays, heavy metallurgy furnaces, material testing rigs, and loading dock.',
    cameras: [],
  },
  SUBSTATION: {
    id: 'SUBSTATION',
    name: 'Electrical Substation',
    subtitle: 'High-Voltage Power Hub',
    category: 'INFRASTRUCTURE',
    type: 'Critical Utility',
    occupancy: 'Restricted (2–5)',
    x: 970,
    y: 90,
    w: 140,
    h: 110,
    center: { x: 1040, y: 145 },
    icon: 'Zap',
    hazardRating: 'HIGH',
    color: '#EAB308',
    description: 'Campus 33kV step-down transformer yard, backup diesel generator battery, and grid switchgear.',
    cameras: [],
  },
  BLOCK_4: {
    id: 'BLOCK_4',
    name: 'Block 4',
    subtitle: 'Computer Science & AI',
    category: 'ACADEMIC',
    type: 'Academic / Tech',
    occupancy: 'High (350–500)',
    x: 100,
    y: 330,
    w: 190,
    h: 150,
    center: { x: 195, y: 405 },
    icon: 'Cpu',
    hazardRating: 'LOW',
    color: '#06B6D4',
    description: 'Data analytics labs, GPU server farm, developer incubators, and smart lecture theaters.',
    cameras: [],
  },
  BLOCK_5: {
    id: 'BLOCK_5',
    name: 'Block 5',
    subtitle: 'Administration & Command',
    category: 'COMMAND',
    type: 'Executive / Central HQ',
    occupancy: 'Medium (200–300)',
    x: 460,
    y: 350,
    w: 250,
    h: 160,
    center: { x: 585, y: 430 },
    icon: 'Building2',
    hazardRating: 'LOW',
    color: '#D4AF37',
    description: 'Chancellor suites, academic affairs registry, central server core, and primary executive briefing room.',
    cameras: [],
  },
  CAFETERIA: {
    id: 'CAFETERIA',
    name: 'Cafeteria',
    subtitle: 'Dining Hall & Food Court',
    category: 'ASSEMBLY',
    type: 'High Occupancy Dining',
    occupancy: 'Critical Crowding (500–800)',
    x: 770,
    y: 340,
    w: 150,
    h: 130,
    center: { x: 845, y: 405 },
    icon: 'Utensils',
    hazardRating: 'MEDIUM',
    color: '#F97316',
    description: 'Two-story main student mess, commercial kitchen gas lines, refrigerated walk-ins, and seating plazas.',
    cameras: [],
  },
  SPORTS_GROUND: {
    id: 'SPORTS_GROUND',
    name: 'Sports Ground',
    subtitle: 'Athletic Arena & Muster Area',
    category: 'ASSEMBLY',
    type: 'Open Area / Evacuation Zone',
    occupancy: 'Variable (0–1500)',
    x: 960,
    y: 240,
    w: 180,
    h: 180,
    center: { x: 1050, y: 330 },
    icon: 'Trophy',
    hazardRating: 'LOW',
    color: '#10B981',
    description: 'Standard 400m synthetic running track, open grass football field, floodlights, and primary campus mass evacuation point.',
    cameras: [],
  },
  HOSTEL_A: {
    id: 'HOSTEL_A',
    name: 'Hostel A',
    subtitle: 'Residential Wing Alpha',
    category: 'RESIDENTIAL',
    type: 'Residential Hall',
    occupancy: 'Very High (450 dorms)',
    x: 90,
    y: 550,
    w: 170,
    h: 150,
    center: { x: 175, y: 625 },
    icon: 'Home',
    hazardRating: 'MEDIUM',
    color: '#8B5CF6',
    description: '4-story student dormitory block, residential common lounge, laundry facility, and warden station.',
    cameras: ['CAM-07', 'CAM-08'],
  },
  HOSTEL_B: {
    id: 'HOSTEL_B',
    name: 'Hostel B',
    subtitle: 'Residential Wing Beta',
    category: 'RESIDENTIAL',
    type: 'Residential Hall',
    occupancy: 'Very High (450 dorms)',
    x: 290,
    y: 550,
    w: 170,
    h: 150,
    center: { x: 375, y: 625 },
    icon: 'Home',
    hazardRating: 'MEDIUM',
    color: '#8B5CF6',
    description: '4-story postgraduate residence hall, study annex, recreation area, and exterior fire escapes.',
    cameras: [],
  },
  AUDITORIUM: {
    id: 'AUDITORIUM',
    name: 'Auditorium',
    subtitle: 'Grand Assembly Hall',
    category: 'ASSEMBLY',
    type: 'High Occupancy Assembly',
    occupancy: 'Mass Gathering (1200 cap)',
    x: 960,
    y: 460,
    w: 160,
    h: 140,
    center: { x: 1040, y: 530 },
    icon: 'Users',
    hazardRating: 'MEDIUM',
    color: '#EC4899',
    description: 'Acoustic stage theater, tiered seating, AV control gallery, and multiple pressurized fire exits.',
    cameras: [],
  },
  SECURITY_ROOM: {
    id: 'SECURITY_ROOM',
    name: 'Security Command',
    subtitle: 'Incident Control Station',
    category: 'COMMAND',
    type: 'Emergency Response Base',
    occupancy: 'Guards on Duty (10–20)',
    x: 520,
    y: 570,
    w: 160,
    h: 100,
    center: { x: 600, y: 620 },
    icon: 'Shield',
    hazardRating: 'LOW',
    color: '#38BDF8',
    description: 'Tactical dispatch desk, CCTV matrix bank, armory, campus alarm master panel, and patrol briefing bay.',
    cameras: [],
  },
  HEALTH_CENTRE: {
    id: 'HEALTH_CENTRE',
    name: 'Health Centre',
    subtitle: 'Medical & Triage Clinic',
    category: 'MEDICAL',
    type: 'Triage & Medical Bay',
    occupancy: 'Clinical Staff (15–30)',
    x: 740,
    y: 570,
    w: 160,
    h: 110,
    center: { x: 820, y: 625 },
    icon: 'HeartPulse',
    hazardRating: 'LOW',
    color: '#10B981',
    description: 'Ambulance docking bay, emergency trauma stabilization ward, pharmacy dispensary, and quarantine rooms.',
    cameras: [],
  },
  MAIN_GATE: {
    id: 'MAIN_GATE',
    name: 'Main Gate',
    subtitle: 'Perimeter Access Portal',
    category: 'PERIMETER',
    type: 'Perimeter Checkpoint',
    occupancy: 'Security Personnel & Vehicles',
    x: 480,
    y: 710,
    w: 240,
    h: 65,
    center: { x: 600, y: 742 },
    icon: 'KeyRound',
    hazardRating: 'LOW',
    color: '#64748B',
    description: 'Primary vehicular boom barriers, RFID biometric turnstiles, visitor verification kiosk, and emergency vehicle lane.',
    cameras: ['CAM-09', 'CAM-10'],
  },
  OTHER: {
    id: 'OTHER',
    name: 'Campus Perimeter',
    subtitle: 'General Grounds & Walkways',
    category: 'OUTDOOR',
    type: 'Exterior Grounds',
    occupancy: 'Variable',
    x: 50,
    y: 50,
    w: 80,
    h: 60,
    center: { x: 90, y: 80 },
    icon: 'MapPin',
    hazardRating: 'LOW',
    color: '#94A3B8',
    description: 'Campus perimeter fence lines, outer service alleys, and auxiliary landscaped gardens.',
    cameras: [],
  },
};

/**
 * Camera anchor coordinates and directional Field-of-View (FOV) angles
 */
export const CAMERA_ANCHORS = {
  'CAM-01': { block: 'BLOCK_1', label: 'CAM-01: Library Entrance', x: 220, y: 260, angle: 90, fov: 65, reach: 55 },
  'CAM-02': { block: 'BLOCK_1', label: 'CAM-02: Library Corridor', x: 160, y: 160, angle: 45, fov: 60, reach: 50 },
  'CAM-03': { block: 'BLOCK_1', label: 'CAM-03: Block 1 Entrance', x: 310, y: 185, angle: 0, fov: 65, reach: 55 },
  'CAM-04': { block: 'BLOCK_2', label: 'CAM-04: Lab Corridor', x: 450, y: 140, angle: 60, fov: 60, reach: 55 },
  'CAM-05': { block: 'BLOCK_2', label: 'CAM-05: Laboratory Entrance', x: 505, y: 255, angle: 90, fov: 70, reach: 60 },
  'CAM-06': { block: 'BLOCK_2', label: 'CAM-06: Block 2 East Entrance', x: 615, y: 175, angle: 10, fov: 65, reach: 55 },
  'CAM-07': { block: 'HOSTEL_A', label: 'CAM-07: Hostel A Main Entrance', x: 175, y: 555, angle: 270, fov: 70, reach: 55 },
  'CAM-08': { block: 'HOSTEL_A', label: 'CAM-08: Hostel A Common Area', x: 230, y: 640, angle: 180, fov: 65, reach: 50 },
  'CAM-09': { block: 'MAIN_GATE', label: 'CAM-09: Entry Gate Vehicle Ingress', x: 550, y: 710, angle: 270, fov: 75, reach: 65 },
  'CAM-10': { block: 'MAIN_GATE', label: 'CAM-10: Visitor Parking & Plaza', x: 660, y: 710, angle: 260, fov: 75, reach: 65 },
};

/**
 * Emergency Team Home Station Coordinates
 */
export const RESOURCE_STATIONS = {
  HEALTH_CENTRE: { x: 820, y: 625, label: 'Health Centre Medical Bay' },
  SECURITY_ROOM: { x: 600, y: 620, label: 'Security Control Hub' },
  BLOCK_2: { x: 505, y: 175, label: 'EHS / Hazmat Station' },
  MAIN_GATE: { x: 600, y: 742, label: 'Perimeter Guard Station' },
  SUBSTATION: { x: 1040, y: 145, label: 'Facilities Maintenance Depot' },
};

/**
 * Campus Ring Road & Pathway Vector Definitions (Blueprint aesthetics)
 */
export const ROAD_PATHS = [
  // Main Central Spine from Main Gate to Central Admin Plaza
  'M 600,710 L 600,510',
  // East-West Central Arterial Avenue
  'M 80,520 L 1120,520',
  // North-South West Campus Connector (Hostel A -> Block 4 -> Block 1)
  'M 200,700 L 200,270 L 200,90',
  // North Academic Ring Road
  'M 120,280 L 1080,280',
  'M 200,80 L 1050,80',
  // North-South East Campus Connector (Main Gate -> Health Centre -> Cafeteria -> Workshops)
  'M 820,700 L 820,260',
  'M 1040,700 L 1040,230',
];
